# Generated by Django 5.2.11 on 2026-04-03 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botanique', '0002_organismphoto_organism'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganismPFAF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edibility_rating', models.PositiveSmallIntegerField(blank=True, help_text='Note comestibilité PFAF (0-5)', null=True)),
                ('medicinal_rating', models.PositiveSmallIntegerField(blank=True, help_text='Note médicinale PFAF (0-5)', null=True)),
                ('edible_uses', models.TextField(blank=True, help_text='Usages comestibles selon PFAF')),
                ('known_hazards', models.TextField(blank=True, help_text='Dangers et toxicité selon PFAF')),
                ('cultivation_details', models.TextField(blank=True, help_text='Détails de culture selon PFAF')),
                ('propagation', models.TextField(blank=True, help_text='Propagation selon PFAF')),
                ('uk_hardiness', models.PositiveSmallIntegerField(blank=True, help_text='Rusticité PFAF échelle UK (1-10)', null=True)),
                ('habit', models.CharField(blank=True, help_text='Port de la plante selon PFAF (Tree, Shrub, Perennial...)', max_length=50)),
                ('pollinators', models.CharField(blank=True, help_text='Pollinisateurs selon PFAF', max_length=200)),
                ('self_fertile', models.BooleanField(blank=True, help_text='Auto-fertile selon PFAF', null=True)),
                ('scented', models.BooleanField(blank=True, help_text='Plante parfumée selon PFAF', null=True)),
                ('date_import', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('import_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pfaf_records', to='botanique.dataimportrun')),
                ('organism', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pfaf', to='botanique.organism')),
            ],
            options={
                'verbose_name': 'Données PFAF',
                'verbose_name_plural': 'Données PFAF',
                'db_table': 'species_organismpfaf',
            },
        ),
    ]
