# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botanique', '0003_organism_pfaf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organismphoto',
            name='image',
            field=models.ImageField(blank=True, upload_to='organism_photos/%Y/%m/'),
        ),
    ]
