# Generated by Django 5.2.11 on 2026-04-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botanique', '0004_organismphoto_image_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organismphoto',
            name='source_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
